# Generated by Django 3.1.14 on 2023-02-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pub_state',
            field=models.BooleanField(default=True),
        ),
    ]
